- gz_topic_name: "/world/andino_world/clock"
  ros_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- gz_topic_name: "/world/andino_world/model/andino/joint_state"
  ros_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS
  max_rate: 50.0

- gz_topic_name: "/model/andino/cmd_vel"
  ros_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/andino/odometry"
  ros_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- gz_topic_name: "/world/andino_world/model/andino/link/rplidar_laser_link/sensor/rplidar/scan"
  ros_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

